// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: quwQo95zDfdBFMtbz7jPTa
// Component: p_FCLC3X1L
import * as React from 'react';

import * as p from '@plasmicapp/react-web';
import * as ph from '@plasmicapp/host';

import {
    hasVariant,
    classNames,
    wrapWithClassName,
    createPlasmicElementProxy,
    makeFragment,
    MultiChoiceArg,
    SingleBooleanChoiceArg,
    SingleChoiceArg,
    pick,
    omit,
    useTrigger,
    StrictProps,
    deriveRenderOpts,
    ensureGlobalVariants,
} from '@plasmicapp/react-web';

import '@plasmicapp/react-web/lib/plasmic.css';

import projectcss from './plasmic_parametric_variant.module.css'; // plasmic-import: quwQo95zDfdBFMtbz7jPTa/projectcss
import sty from './PlasmicArrow.module.css'; // plasmic-import: p_FCLC3X1L/css

import Icon3Icon from './icons/PlasmicIcon__Icon3'; // plasmic-import: IHJlVtaRri/icon

export type PlasmicArrow__VariantMembers = {};

export type PlasmicArrow__VariantsArgs = {};
type VariantPropType = keyof PlasmicArrow__VariantsArgs;
export const PlasmicArrow__VariantProps = new Array<VariantPropType>();

export type PlasmicArrow__ArgsType = {};
type ArgPropType = keyof PlasmicArrow__ArgsType;
export const PlasmicArrow__ArgProps = new Array<ArgPropType>();

export type PlasmicArrow__OverridesType = {
    root?: p.Flex<'div'>;
    svg?: p.Flex<'svg'>;
};

export interface DefaultArrowProps {
    className?: string;
}

function PlasmicArrow__RenderFunc(props: {
    variants: PlasmicArrow__VariantsArgs;
    args: PlasmicArrow__ArgsType;
    overrides: PlasmicArrow__OverridesType;

    forNode?: string;
}) {
    const {variants, args, overrides, forNode} = props;
    const $props = props.args;

    return (
        true ? (
            <p.Stack
                as={'div'}
                data-plasmic-name={'root'}
                data-plasmic-override={overrides.root}
                data-plasmic-root={true}
                data-plasmic-for-node={forNode}
                hasGap={true}
                className={classNames(
                    projectcss.all,
                    projectcss.root_reset,
                    projectcss.plasmic_default_styles,
                    projectcss.plasmic_mixins,
                    projectcss.plasmic_tokens,
                    sty.root
                )}
            >
                <p.Stack as={'div'} hasGap={true} className={classNames(projectcss.all, sty.freeBox__ghKe)}>
                    <div className={classNames(projectcss.all, sty.freeBox__m4EfZ)} />

                    <div className={classNames(projectcss.all, sty.freeBox___9Rqbd)} />

                    <div className={classNames(projectcss.all, sty.freeBox__dr59P)} />

                    <div className={classNames(projectcss.all, sty.freeBox__ij63F)} />

                    <div className={classNames(projectcss.all, sty.freeBox___2MLL)} />

                    <div className={classNames(projectcss.all, sty.freeBox__mtMk)} />

                    <div className={classNames(projectcss.all, sty.freeBox__ckr3E)} />

                    <div className={classNames(projectcss.all, sty.freeBox__zgPvQ)} />

                    <div className={classNames(projectcss.all, sty.freeBox__fo6O)} />

                    <div className={classNames(projectcss.all, sty.freeBox__xu6Xs)} />

                    <div className={classNames(projectcss.all, sty.freeBox__hRnc)} />

                    <div className={classNames(projectcss.all, sty.freeBox__x5XAo)} />

                    <div className={classNames(projectcss.all, sty.freeBox__eRgqU)} />

                    <div className={classNames(projectcss.all, sty.freeBox__s3ID)} />

                    <div className={classNames(projectcss.all, sty.freeBox__z6GAx)} />

                    <div className={classNames(projectcss.all, sty.freeBox__w4YI)} />

                    <div className={classNames(projectcss.all, sty.freeBox__xf8GP)} />
                </p.Stack>

                {true ? (
                    <div className={classNames(projectcss.all, sty.freeBox__nCr3U)}>
                        <Icon3Icon
                            data-plasmic-name={'svg'}
                            data-plasmic-override={overrides.svg}
                            className={classNames(projectcss.all, sty.svg)}
                            role={'img'}
                        />
                    </div>
                ) : null}
            </p.Stack>
        ) : null
    ) as React.ReactElement | null;
}

const PlasmicDescendants = {
    root: ['root', 'svg'],
    svg: ['svg'],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
    root: 'div';
    svg: 'svg';
};

type ReservedPropsType = 'variants' | 'args' | 'overrides';
type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicArrow__OverridesType, DescendantsType<T>>;
type NodeComponentProps<T extends NodeNameType> =
    // Explicitly specify variants, args, and overrides as objects
    {
        variants?: PlasmicArrow__VariantsArgs;
        args?: PlasmicArrow__ArgsType;
        overrides?: NodeOverridesType<T>;
    } & Omit<PlasmicArrow__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
        // Specify args directly as props
        Omit<PlasmicArrow__ArgsType, ReservedPropsType> &
        // Specify overrides for each element directly as props
        Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType> &
        // Specify props for the root element
        Omit<
            Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
            ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
        >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
    type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
    const func = function <T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
            name: nodeName,
            descendantNames: [...PlasmicDescendants[nodeName]],
            internalArgPropNames: PlasmicArrow__ArgProps,
            internalVariantPropNames: PlasmicArrow__VariantProps,
        });

        return PlasmicArrow__RenderFunc({
            variants,
            args,
            overrides,
            forNode: nodeName,
        });
    };
    if (nodeName === 'root') {
        func.displayName = 'PlasmicArrow';
    } else {
        func.displayName = `PlasmicArrow.${nodeName}`;
    }
    return func;
}

export const PlasmicArrow = Object.assign(
    // Top-level PlasmicArrow renders the root element
    makeNodeComponent('root'),
    {
        // Helper components rendering sub-elements
        svg: makeNodeComponent('svg'),

        // Metadata about props expected for PlasmicArrow
        internalVariantProps: PlasmicArrow__VariantProps,
        internalArgProps: PlasmicArrow__ArgProps,
    }
);

export default PlasmicArrow;
/* prettier-ignore-end */
