// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: quwQo95zDfdBFMtbz7jPTa
// Component: gfQV_fY2gI
import * as React from 'react';

import * as p from '@plasmicapp/react-web';
import * as ph from '@plasmicapp/host';

import {
    hasVariant,
    classNames,
    wrapWithClassName,
    createPlasmicElementProxy,
    makeFragment,
    MultiChoiceArg,
    SingleBooleanChoiceArg,
    SingleChoiceArg,
    pick,
    omit,
    useTrigger,
    StrictProps,
    deriveRenderOpts,
    ensureGlobalVariants,
} from '@plasmicapp/react-web';

import '@plasmicapp/react-web/lib/plasmic.css';

import projectcss from './plasmic_parametric_variant.module.css'; // plasmic-import: quwQo95zDfdBFMtbz7jPTa/projectcss
import sty from './PlasmicRemove.module.css'; // plasmic-import: gfQV_fY2gI/css

import TipscloseIcon from './icons/PlasmicIcon__Tipsclose'; // plasmic-import: AiBjhaw1Qt/icon

export type PlasmicRemove__VariantMembers = {};

export type PlasmicRemove__VariantsArgs = {};
type VariantPropType = keyof PlasmicRemove__VariantsArgs;
export const PlasmicRemove__VariantProps = new Array<VariantPropType>();

export type PlasmicRemove__ArgsType = {};
type ArgPropType = keyof PlasmicRemove__ArgsType;
export const PlasmicRemove__ArgProps = new Array<ArgPropType>();

export type PlasmicRemove__OverridesType = {
    root?: p.Flex<'div'>;
    svg?: p.Flex<'svg'>;
};

export interface DefaultRemoveProps {
    className?: string;
}

function PlasmicRemove__RenderFunc(props: {
    variants: PlasmicRemove__VariantsArgs;
    args: PlasmicRemove__ArgsType;
    overrides: PlasmicRemove__OverridesType;

    forNode?: string;
}) {
    const {variants, args, overrides, forNode} = props;
    const $props = props.args;

    return (
        <div
            data-plasmic-name={'root'}
            data-plasmic-override={overrides.root}
            data-plasmic-root={true}
            data-plasmic-for-node={forNode}
            className={classNames(
                projectcss.all,
                projectcss.root_reset,
                projectcss.plasmic_default_styles,
                projectcss.plasmic_mixins,
                projectcss.plasmic_tokens,
                sty.root
            )}
        >
            <TipscloseIcon
                data-plasmic-name={'svg'}
                data-plasmic-override={overrides.svg}
                className={classNames(projectcss.all, sty.svg)}
                role={'img'}
            />
        </div>
    ) as React.ReactElement | null;
}

const PlasmicDescendants = {
    root: ['root', 'svg'],
    svg: ['svg'],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
    root: 'div';
    svg: 'svg';
};

type ReservedPropsType = 'variants' | 'args' | 'overrides';
type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicRemove__OverridesType, DescendantsType<T>>;
type NodeComponentProps<T extends NodeNameType> =
    // Explicitly specify variants, args, and overrides as objects
    {
        variants?: PlasmicRemove__VariantsArgs;
        args?: PlasmicRemove__ArgsType;
        overrides?: NodeOverridesType<T>;
    } & Omit<PlasmicRemove__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
        // Specify args directly as props
        Omit<PlasmicRemove__ArgsType, ReservedPropsType> &
        // Specify overrides for each element directly as props
        Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType> &
        // Specify props for the root element
        Omit<
            Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
            ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
        >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
    type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
    const func = function <T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
            name: nodeName,
            descendantNames: [...PlasmicDescendants[nodeName]],
            internalArgPropNames: PlasmicRemove__ArgProps,
            internalVariantPropNames: PlasmicRemove__VariantProps,
        });

        return PlasmicRemove__RenderFunc({
            variants,
            args,
            overrides,
            forNode: nodeName,
        });
    };
    if (nodeName === 'root') {
        func.displayName = 'PlasmicRemove';
    } else {
        func.displayName = `PlasmicRemove.${nodeName}`;
    }
    return func;
}

export const PlasmicRemove = Object.assign(
    // Top-level PlasmicRemove renders the root element
    makeNodeComponent('root'),
    {
        // Helper components rendering sub-elements
        svg: makeNodeComponent('svg'),

        // Metadata about props expected for PlasmicRemove
        internalVariantProps: PlasmicRemove__VariantProps,
        internalArgProps: PlasmicRemove__ArgProps,
    }
);

export default PlasmicRemove;
/* prettier-ignore-end */
