// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: quwQo95zDfdBFMtbz7jPTa
// Component: j_YCk93j1o
import * as React from 'react';

import * as p from '@plasmicapp/react-web';
import * as ph from '@plasmicapp/host';

import {
    hasVariant,
    classNames,
    wrapWithClassName,
    createPlasmicElementProxy,
    makeFragment,
    MultiChoiceArg,
    SingleBooleanChoiceArg,
    SingleChoiceArg,
    pick,
    omit,
    useTrigger,
    StrictProps,
    deriveRenderOpts,
    ensureGlobalVariants,
} from '@plasmicapp/react-web';

import '@plasmicapp/react-web/lib/plasmic.css';

import projectcss from './plasmic_parametric_variant.module.css'; // plasmic-import: quwQo95zDfdBFMtbz7jPTa/projectcss
import sty from './PlasmicBaseVariant.module.css'; // plasmic-import: j_YCk93j1o/css

export type PlasmicBaseVariant__VariantMembers = {};

export type PlasmicBaseVariant__VariantsArgs = {};
type VariantPropType = keyof PlasmicBaseVariant__VariantsArgs;
export const PlasmicBaseVariant__VariantProps = new Array<VariantPropType>();

export type PlasmicBaseVariant__ArgsType = {};
type ArgPropType = keyof PlasmicBaseVariant__ArgsType;
export const PlasmicBaseVariant__ArgProps = new Array<ArgPropType>();

export type PlasmicBaseVariant__OverridesType = {
    root?: p.Flex<'div'>;
    oldSetSelection?: p.Flex<'div'>;
    text?: p.Flex<'div'>;
};

export interface DefaultBaseVariantProps {
    className?: string;
}

function PlasmicBaseVariant__RenderFunc(props: {
    variants: PlasmicBaseVariant__VariantsArgs;
    args: PlasmicBaseVariant__ArgsType;
    overrides: PlasmicBaseVariant__OverridesType;

    forNode?: string;
}) {
    const {variants, args, overrides, forNode} = props;
    const $props = props.args;

    return (
        <React.Fragment>
            {}
            {}

            <div className={projectcss.plasmic_page_wrapper}>
                <div
                    data-plasmic-name={'root'}
                    data-plasmic-override={overrides.root}
                    data-plasmic-root={true}
                    data-plasmic-for-node={forNode}
                    className={classNames(
                        projectcss.all,
                        projectcss.root_reset,
                        projectcss.plasmic_default_styles,
                        projectcss.plasmic_mixins,
                        projectcss.plasmic_tokens,
                        sty.root
                    )}
                >
                    <div
                        data-plasmic-name={'oldSetSelection'}
                        data-plasmic-override={overrides.oldSetSelection}
                        className={classNames(projectcss.all, sty.oldSetSelection)}
                    >
                        <div
                            data-plasmic-name={'text'}
                            data-plasmic-override={overrides.text}
                            className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
                        >
                            {'this is a base varaint, any changes made to base will be reflected to all varaints'}
                        </div>
                    </div>
                </div>
            </div>
        </React.Fragment>
    ) as React.ReactElement | null;
}

const PlasmicDescendants = {
    root: ['root', 'oldSetSelection', 'text'],
    oldSetSelection: ['oldSetSelection', 'text'],
    text: ['text'],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
    root: 'div';
    oldSetSelection: 'div';
    text: 'div';
};

type ReservedPropsType = 'variants' | 'args' | 'overrides';
type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicBaseVariant__OverridesType, DescendantsType<T>>;
type NodeComponentProps<T extends NodeNameType> =
    // Explicitly specify variants, args, and overrides as objects
    {
        variants?: PlasmicBaseVariant__VariantsArgs;
        args?: PlasmicBaseVariant__ArgsType;
        overrides?: NodeOverridesType<T>;
    } & Omit<PlasmicBaseVariant__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
        // Specify args directly as props
        Omit<PlasmicBaseVariant__ArgsType, ReservedPropsType> &
        // Specify overrides for each element directly as props
        Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType> &
        // Specify props for the root element
        Omit<
            Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
            ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
        >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
    type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
    const func = function <T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
            name: nodeName,
            descendantNames: [...PlasmicDescendants[nodeName]],
            internalArgPropNames: PlasmicBaseVariant__ArgProps,
            internalVariantPropNames: PlasmicBaseVariant__VariantProps,
        });

        return PlasmicBaseVariant__RenderFunc({
            variants,
            args,
            overrides,
            forNode: nodeName,
        });
    };
    if (nodeName === 'root') {
        func.displayName = 'PlasmicBaseVariant';
    } else {
        func.displayName = `PlasmicBaseVariant.${nodeName}`;
    }
    return func;
}

export const PlasmicBaseVariant = Object.assign(
    // Top-level PlasmicBaseVariant renders the root element
    makeNodeComponent('root'),
    {
        // Helper components rendering sub-elements
        oldSetSelection: makeNodeComponent('oldSetSelection'),
        text: makeNodeComponent('text'),

        // Metadata about props expected for PlasmicBaseVariant
        internalVariantProps: PlasmicBaseVariant__VariantProps,
        internalArgProps: PlasmicBaseVariant__ArgProps,
    }
);

export default PlasmicBaseVariant;
/* prettier-ignore-end */
