// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: quwQo95zDfdBFMtbz7jPTa
// Component: ymIixQqbuZS
import * as React from 'react';

import * as p from '@plasmicapp/react-web';
import * as ph from '@plasmicapp/host';

import {
    hasVariant,
    classNames,
    wrapWithClassName,
    createPlasmicElementProxy,
    makeFragment,
    MultiChoiceArg,
    SingleBooleanChoiceArg,
    SingleChoiceArg,
    pick,
    omit,
    useTrigger,
    StrictProps,
    deriveRenderOpts,
    ensureGlobalVariants,
} from '@plasmicapp/react-web';
import RadioItem from '../../RadioItem'; // plasmic-import: TRE54cYrIj/component
import Button from '../../Button'; // plasmic-import: cSQMAe0reF/component

import '@plasmicapp/react-web/lib/plasmic.css';

import projectcss from './plasmic_parametric_variant.module.css'; // plasmic-import: quwQo95zDfdBFMtbz7jPTa/projectcss
import sty from './PlasmicCreateInteractiveState.module.css'; // plasmic-import: ymIixQqbuZS/css

import SeparatorIcon from './icons/PlasmicIcon__Separator'; // plasmic-import: _JYn_hvct4/icon

export type PlasmicCreateInteractiveState__VariantMembers = {};

export type PlasmicCreateInteractiveState__VariantsArgs = {};
type VariantPropType = keyof PlasmicCreateInteractiveState__VariantsArgs;
export const PlasmicCreateInteractiveState__VariantProps = new Array<VariantPropType>();

export type PlasmicCreateInteractiveState__ArgsType = {};
type ArgPropType = keyof PlasmicCreateInteractiveState__ArgsType;
export const PlasmicCreateInteractiveState__ArgProps = new Array<ArgPropType>();

export type PlasmicCreateInteractiveState__OverridesType = {
    root?: p.Flex<'div'>;
    content?: p.Flex<'div'>;
    frame53?: p.Flex<'div'>;
    frame50?: p.Flex<'div'>;
    frame18?: p.Flex<'div'>;
    type?: p.Flex<'div'>;
    text?: p.Flex<'div'>;
    frame16?: p.Flex<'div'>;
    svg?: p.Flex<'svg'>;
    freeBox?: p.Flex<'div'>;
    button?: p.Flex<'div'>;
    createVariant?: p.Flex<typeof Button>;
};

export interface DefaultCreateInteractiveStateProps {
    className?: string;
}

function PlasmicCreateInteractiveState__RenderFunc(props: {
    variants: PlasmicCreateInteractiveState__VariantsArgs;
    args: PlasmicCreateInteractiveState__ArgsType;
    overrides: PlasmicCreateInteractiveState__OverridesType;

    forNode?: string;
}) {
    const {variants, args, overrides, forNode} = props;
    const $props = props.args;

    return (
        <React.Fragment>
            {}
            {}

            <div className={projectcss.plasmic_page_wrapper}>
                <div
                    data-plasmic-name={'root'}
                    data-plasmic-override={overrides.root}
                    data-plasmic-root={true}
                    data-plasmic-for-node={forNode}
                    className={classNames(
                        projectcss.all,
                        projectcss.root_reset,
                        projectcss.plasmic_default_styles,
                        projectcss.plasmic_mixins,
                        projectcss.plasmic_tokens,
                        sty.root
                    )}
                >
                    <div
                        data-plasmic-name={'content'}
                        data-plasmic-override={overrides.content}
                        className={classNames(projectcss.all, sty.content)}
                    >
                        <p.Stack
                            as={'div'}
                            data-plasmic-name={'frame53'}
                            data-plasmic-override={overrides.frame53}
                            hasGap={true}
                            className={classNames(projectcss.all, sty.frame53)}
                        >
                            <p.Stack
                                as={'div'}
                                data-plasmic-name={'frame50'}
                                data-plasmic-override={overrides.frame50}
                                hasGap={true}
                                className={classNames(projectcss.all, sty.frame50)}
                            >
                                <div
                                    data-plasmic-name={'frame18'}
                                    data-plasmic-override={overrides.frame18}
                                    className={classNames(projectcss.all, sty.frame18)}
                                >
                                    <div
                                        data-plasmic-name={'type'}
                                        data-plasmic-override={overrides.type}
                                        className={classNames(projectcss.all, sty.type)}
                                    >
                                        <div
                                            data-plasmic-name={'text'}
                                            data-plasmic-override={overrides.text}
                                            className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
                                        >
                                            {'State'}
                                        </div>
                                    </div>

                                    <div
                                        data-plasmic-name={'frame16'}
                                        data-plasmic-override={overrides.frame16}
                                        className={classNames(projectcss.all, sty.frame16)}
                                    >
                                        <RadioItem
                                            active={true}
                                            className={classNames('__wab_instance', sty.radioItem__aQ0M)}
                                        >
                                            {'Hover'}
                                        </RadioItem>

                                        <RadioItem className={classNames('__wab_instance', sty.radioItem__hqAb)}>
                                            {'Pressed'}
                                        </RadioItem>
                                    </div>
                                </div>
                            </p.Stack>

                            <SeparatorIcon
                                data-plasmic-name={'svg'}
                                data-plasmic-override={overrides.svg}
                                className={classNames(projectcss.all, sty.svg)}
                                role={'img'}
                            />
                        </p.Stack>

                        <div
                            data-plasmic-name={'freeBox'}
                            data-plasmic-override={overrides.freeBox}
                            className={classNames(projectcss.all, sty.freeBox)}
                        >
                            <p.Stack
                                as={'div'}
                                data-plasmic-name={'button'}
                                data-plasmic-override={overrides.button}
                                hasGap={true}
                                className={classNames(projectcss.all, sty.button)}
                            >
                                <Button
                                    data-plasmic-name={'createVariant'}
                                    data-plasmic-override={overrides.createVariant}
                                    className={classNames('__wab_instance', sty.createVariant)}
                                    text={'Create Interactive State'}
                                />
                            </p.Stack>
                        </div>
                    </div>
                </div>
            </div>
        </React.Fragment>
    ) as React.ReactElement | null;
}

const PlasmicDescendants = {
    root: [
        'root',
        'content',
        'frame53',
        'frame50',
        'frame18',
        'type',
        'text',
        'frame16',
        'svg',
        'freeBox',
        'button',
        'createVariant',
    ],
    content: [
        'content',
        'frame53',
        'frame50',
        'frame18',
        'type',
        'text',
        'frame16',
        'svg',
        'freeBox',
        'button',
        'createVariant',
    ],
    frame53: ['frame53', 'frame50', 'frame18', 'type', 'text', 'frame16', 'svg'],
    frame50: ['frame50', 'frame18', 'type', 'text', 'frame16'],
    frame18: ['frame18', 'type', 'text', 'frame16'],
    type: ['type', 'text'],
    text: ['text'],
    frame16: ['frame16'],
    svg: ['svg'],
    freeBox: ['freeBox', 'button', 'createVariant'],
    button: ['button', 'createVariant'],
    createVariant: ['createVariant'],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
    root: 'div';
    content: 'div';
    frame53: 'div';
    frame50: 'div';
    frame18: 'div';
    type: 'div';
    text: 'div';
    frame16: 'div';
    svg: 'svg';
    freeBox: 'div';
    button: 'div';
    createVariant: typeof Button;
};

type ReservedPropsType = 'variants' | 'args' | 'overrides';
type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicCreateInteractiveState__OverridesType, DescendantsType<T>>;
type NodeComponentProps<T extends NodeNameType> =
    // Explicitly specify variants, args, and overrides as objects
    {
        variants?: PlasmicCreateInteractiveState__VariantsArgs;
        args?: PlasmicCreateInteractiveState__ArgsType;
        overrides?: NodeOverridesType<T>;
    } & Omit<PlasmicCreateInteractiveState__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
        // Specify args directly as props
        Omit<PlasmicCreateInteractiveState__ArgsType, ReservedPropsType> &
        // Specify overrides for each element directly as props
        Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType> &
        // Specify props for the root element
        Omit<
            Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
            ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
        >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
    type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
    const func = function <T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
            name: nodeName,
            descendantNames: [...PlasmicDescendants[nodeName]],
            internalArgPropNames: PlasmicCreateInteractiveState__ArgProps,
            internalVariantPropNames: PlasmicCreateInteractiveState__VariantProps,
        });

        return PlasmicCreateInteractiveState__RenderFunc({
            variants,
            args,
            overrides,
            forNode: nodeName,
        });
    };
    if (nodeName === 'root') {
        func.displayName = 'PlasmicCreateInteractiveState';
    } else {
        func.displayName = `PlasmicCreateInteractiveState.${nodeName}`;
    }
    return func;
}

export const PlasmicCreateInteractiveState = Object.assign(
    // Top-level PlasmicCreateInteractiveState renders the root element
    makeNodeComponent('root'),
    {
        // Helper components rendering sub-elements
        content: makeNodeComponent('content'),
        frame53: makeNodeComponent('frame53'),
        frame50: makeNodeComponent('frame50'),
        frame18: makeNodeComponent('frame18'),
        type: makeNodeComponent('type'),
        text: makeNodeComponent('text'),
        frame16: makeNodeComponent('frame16'),
        svg: makeNodeComponent('svg'),
        freeBox: makeNodeComponent('freeBox'),
        button: makeNodeComponent('button'),
        createVariant: makeNodeComponent('createVariant'),

        // Metadata about props expected for PlasmicCreateInteractiveState
        internalVariantProps: PlasmicCreateInteractiveState__VariantProps,
        internalArgProps: PlasmicCreateInteractiveState__ArgProps,
    }
);

export default PlasmicCreateInteractiveState;
/* prettier-ignore-end */
