// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from 'react';
import {PlasmicHomepage, DefaultHomepageProps} from './plasmic/parametric_variant/PlasmicHomepage';
import {HTMLElementRefOf} from '@plasmicapp/react-web';

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface HomepageProps extends Omit<DefaultHomepageProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultHomepageProps altogether and have
// total control over the props for your component.
export interface HomepageProps extends DefaultHomepageProps {}

function Homepage_(props: HomepageProps, ref: HTMLElementRefOf<'div'>) {


    return <PlasmicHomepage root={{ref}} 
    createComponentSet={{
        props:{
            onClick: (e: React.MouseEvent<HTMLDivElement>) => {
                console.log('clicked');
            }
        }
    }}
    {...props} />;
}

const Homepage = React.forwardRef(Homepage_);
export default Homepage;
