// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from 'react';
import { PlasmicInspectDiff, DefaultInspectDiffProps } from './plasmic/parametric_variant/PlasmicInspectDiff';
import { HTMLElementRefOf } from '@plasmicapp/react-web';
import { useEffect } from 'react';
import { handleEvent } from '../app/uiMessageHandler';
import Layer from './Layer';
import Diff from './Diff';

export interface InspectDiffProps extends DefaultInspectDiffProps { }

function InspectDiff_(props: InspectDiffProps, ref: HTMLElementRefOf<'div'>) {

    let [diffs, setDiffs] = React.useState({});
    useEffect(() => {
        handleEvent('updateDiff', (d) => {
            setDiffs(d);
            // console.log("d = ",d)

        });

    }, []);

    return <PlasmicInspectDiff
        root={{ ref }}
        confirm={{
            props: {
                isHidden: Object.keys(diffs).length > 0
            }
        }}
        diffContent={{
            props: {
                empty: Object.keys(diffs).length === 0,
            },
            wrapChildren: (children) => {
                if (Object.keys(diffs).length > 0) {
                    return Object.keys(diffs["children"]).map(k => {

                        return <Layer layerName={k} items={Object.keys(diffs["children"][k]).map(eachKey => {
                            return (
                                <Diff key={eachKey} name={eachKey} value={diffs["children"][k][eachKey]["@right"]} />

                            )
                        })} />
                    })
                }

            }
        }}
        
        {...props} />;
}

const InspectDiff = React.forwardRef(InspectDiff_);
export default InspectDiff;
